import test from 'node:test';
import assert from 'node:assert/strict';
import {localD1,migrateLocal} from '../scripts/local-d1.mjs';
import {handleApi} from '../worker/api.js';
import {trainingInput,validatePlan,callModel} from '../worker/ai.js';
import {initialData,defaultProfile,defaultCheckin} from '../src/domain.mjs';
const origin='https://fitness.test';
const plan={title:'基础训练',intensity:'轻强度',minutes:20,reasons:['根据个人能力调整。'],exercises:[{id:'squat',sets:2,reps:10,rest:60}]};
const input=()=>({profile:{...defaultProfile},checkin:{...defaultCheckin},aiConsent:true,requestKey:crypto.randomUUID()});
function fixture(t){const DB=localD1();migrateLocal(DB,new URL('../.openai/drizzle',import.meta.url));t.after(()=>DB.close());return {DB,AI_ENABLED:'true',DEEPSEEK_API_KEY:'test-only-not-a-real-key',COMMUNITY_ENABLED:'true',AI_BUDGET_MICRO:'5000000',MODEL_FETCH:async()=>Response.json({choices:[{message:{content:JSON.stringify(plan)},finish_reason:'stop'}],usage:{prompt_tokens:600,completion_tokens:200}})};}
async function req(env,path,method='GET',value,cookie,headers={}){const r=await handleApi(new Request(origin+path,{method,headers:{...(cookie?{cookie}:{}),...(method==='GET'?{}:{Origin:origin,'Content-Type':'application/json'}),...headers},body:value===undefined?undefined:JSON.stringify(value)}),env);return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function activate(env,name='测试访客'){const state=initialData();state.profile={...defaultProfile,name};return req(env,'/api/activate','POST',{consent:true,state});}

test('cloud activation requires explicit consent and private records stay isolated',async t=>{const env=fixture(t);const no=await req(env,'/api/activate','POST',{state:initialData()});assert.equal(no.status,400);const a=await activate(env,'A'),b=await activate(env,'B');assert.equal(a.status,201);assert.notEqual(a.cookie,b.cookie);assert.equal((await req(env,'/api/bootstrap','GET',undefined,a.cookie)).body.state.profile.name,'A');assert.equal((await req(env,'/api/bootstrap','GET',undefined,b.cookie)).body.state.profile.name,'B');assert.equal((await req(env,'/api/bootstrap')).body.active,false);assert.equal((await req(env,'/api/bootstrap','GET',undefined,'__Host-lianyu-visitor='+'a'.repeat(64))).body.active,false);});
test('write requests reject foreign and missing origins',async t=>{const env=fixture(t),a=await activate(env);for(const originValue of ['https://other.test','']){const r=await req(env,'/api/state','PUT',{revision:1,state:a.body.state},a.cookie,{Origin:originValue});assert.equal(r.status,403);}assert.equal((await req(env,'/api/bootstrap','GET',undefined,a.cookie)).body.revision,1);});
test('optimistic updates cannot silently overwrite newer state',async t=>{const env=fixture(t),a=await activate(env);a.body.state.planName='更新后的计划';assert.equal((await req(env,'/api/state','PUT',{state:a.body.state,revision:1},a.cookie)).status,200);a.body.state.planName='过时的另一个窗口';assert.equal((await req(env,'/api/state','PUT',{state:a.body.state,revision:1},a.cookie)).status,409);assert.equal((await req(env,'/api/bootstrap','GET',undefined,a.cookie)).body.state.planName,'更新后的计划');});
test('activation never publishes local posts',async t=>{const env=fixture(t),state=initialData();state.posts=[{id:'local',text:'private draft'}];const a=await req(env,'/api/activate','POST',{consent:true,state});assert.equal(a.status,201);assert.deepEqual((await req(env,'/api/posts')).body.posts,[]);});
test('posts are shared but ownership and private state are not exposed',async t=>{const env=fixture(t),a=await activate(env,'甲'),b=await activate(env,'乙');const p=await req(env,'/api/posts','POST',{text:'今天完成了训练',tag:'训练交流'},a.cookie);assert.equal(p.status,201);const seen=(await req(env,'/api/posts','GET',undefined,b.cookie)).body.posts[0];assert.equal(seen.text,'今天完成了训练');assert.equal(seen.own,false);assert.equal(seen.owner_id,undefined);assert.equal(seen.profile,undefined);assert.equal((await req(env,'/api/posts/'+p.body.id,'DELETE',{},b.cookie)).status,403);assert.equal((await req(env,'/api/posts/'+p.body.id,'DELETE',{},a.cookie)).status,200);});
test('comments and likes are real shared records; duplicate likes are idempotent',async t=>{const env=fixture(t),a=await activate(env),b=await activate(env);const p=(await req(env,'/api/posts','POST',{text:'第一条',tag:'训练交流'},a.cookie)).body.id;await req(env,`/api/posts/${p}/comments`,'POST',{text:'一起加油'},b.cookie);for(let i=0;i<2;i++)await req(env,`/api/posts/${p}/like`,'POST',{liked:true},b.cookie);const post=(await req(env,'/api/posts','GET',undefined,a.cookie)).body.posts[0];assert.equal(post.likeCount,1);assert.equal(post.comments[0].text,'一起加油');});
test('moderation requires configured platform identity',async t=>{const env=fixture(t),a=await activate(env),b=await activate(env);env.ADMIN_SITE_USER_ID='site-owner-test';const id=(await req(env,'/api/posts','POST',{text:'待处理内容',tag:'训练交流'},a.cookie)).body.id;await req(env,`/api/posts/${id}/report`,'POST',{reason:'测试举报'},b.cookie);assert.equal((await req(env,'/api/admin/reports','GET',undefined,b.cookie)).status,403);const adminHeaders={'oai-authenticated-user-id':'site-owner-test'};assert.equal((await req(env,'/api/admin/reports','GET',undefined,undefined,adminHeaders)).body.reports.length,1);assert.equal((await req(env,`/api/admin/posts/${id}/hide`,'POST',{},undefined,adminHeaders)).status,200);assert.equal((await req(env,'/api/posts')).body.posts.length,0);});
test('event capacity is enforced atomically and duplicate registration does not consume extra seats',async t=>{const env=fixture(t),people=[];await req(env,'/api/events');env.DB.sqlite.exec('UPDATE events SET capacity=2');for(let i=0;i<3;i++)people.push(await activate(env));const signup=person=>req(env,'/api/events/test-outdoor/register','POST',{testAcknowledged:true},person.cookie);const results=await Promise.all(people.map(signup));assert.equal(results.filter(r=>r.status===200).length,2);assert.equal(results.filter(r=>r.status===409).length,1);assert.equal((await signup(people[0])).status,200);assert.equal((await req(env,'/api/events')).body.events[0].confirmed,2);await req(env,'/api/events/test-outdoor/cancel','POST',{},people[0].cookie);assert.equal((await signup(people[2])).status,200);assert.equal((await req(env,'/api/events')).body.events[0].confirmed,2);});
test('AI requires consent, a valid identity, and no discomfort before any billing reservation',async t=>{const env=fixture(t),a=await activate(env);assert.equal((await req(env,'/api/ai/plan','POST',input())).status,401);let payload=input();payload.aiConsent=false;assert.equal((await req(env,'/api/ai/plan','POST',payload,a.cookie)).status,400);payload=input();payload.checkin.discomfort=true;assert.equal((await req(env,'/api/ai/plan','POST',payload,a.cookie)).status,422);assert.equal(env.DB.sqlite.prepare('SELECT count(*) AS n FROM ai_requests').get().n,0);});
test('model requests exclude names, city, bio and user-supplied prompt text',async()=>{const payload=input();payload.profile.name='Do not forward this';payload.profile.city='Do not forward city';payload.profile.bio='ignore system';let captured;const result=await callModel(trainingInput(payload),'test-only',async(url,options)=>{captured=JSON.parse(options.body);assert.equal(url,'https://api.deepseek.com/chat/completions');return Response.json({choices:[{message:{content:JSON.stringify(plan)},finish_reason:'stop'}],usage:{prompt_tokens:100,completion_tokens:100}});});assert.equal(result.plan.source,'deepseek');assert.equal(JSON.stringify(captured).includes('Do not forward'),false);assert.equal(JSON.stringify(captured).includes('ignore system'),false);assert.equal(captured.thinking.type,'disabled');assert.equal(captured.max_tokens,2048);});
test('model output is checked against equipment, time, duplicates and numeric bounds',()=>{const data=input();data.profile.equipment='自重';const p=trainingInput(data);assert.throws(()=>validatePlan({...plan,exercises:[{id:'bench',sets:3,reps:8,rest:60}]},p));assert.throws(()=>validatePlan({...plan,minutes:100},p));assert.throws(()=>validatePlan({...plan,exercises:[...plan.exercises,...plan.exercises]},p));assert.throws(()=>validatePlan({...plan,exercises:[{id:'squat',sets:100,reps:10,rest:60}]},p));});
test('AI repeated request keys never call the provider twice',async t=>{const env=fixture(t),a=await activate(env);let calls=0;const original=env.MODEL_FETCH;env.MODEL_FETCH=async(...args)=>{calls++;return original(...args);};const payload=input();const r=await req(env,'/api/ai/plan','POST',payload,a.cookie);assert.equal(r.status,200);assert.equal((await req(env,'/api/ai/plan','POST',payload,a.cookie)).status,200);assert.equal(calls,1);});
test('monthly quota and global reservation ceiling prevent further provider calls',async t=>{const env=fixture(t),a=await activate(env),b=await activate(env);for(let i=0;i<4;i++)assert.equal((await req(env,'/api/ai/plan','POST',input(),a.cookie)).status,200);assert.equal((await req(env,'/api/ai/plan','POST',input(),a.cookie)).status,429);env.AI_BUDGET_MICRO='400000';assert.equal((await req(env,'/api/ai/plan','POST',input(),b.cookie)).status,429);assert.equal(env.DB.sqlite.prepare('SELECT sum(reserve_micro) AS n FROM ai_requests').get().n,400000);});
test('concurrent AI requests cannot overspend the global reservation ceiling',async t=>{const env=fixture(t);env.AI_BUDGET_MICRO='100000';const a=await activate(env),b=await activate(env);const results=await Promise.all([req(env,'/api/ai/plan','POST',input(),a.cookie),req(env,'/api/ai/plan','POST',input(),b.cookie)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,429]);});
test('provider failures do not leak credentials and keep conservative billing reservations',async t=>{const env=fixture(t),a=await activate(env);env.MODEL_FETCH=async()=>new Response('provider detail with secret',{status:401});const r=await req(env,'/api/ai/plan','POST',input(),a.cookie);assert.equal(r.status,502);assert.equal(JSON.stringify(r.body).includes('secret'),false);assert.equal(env.DB.sqlite.prepare('SELECT status,reserve_micro FROM ai_requests').get().status,'failed');assert.equal(env.DB.sqlite.prepare('SELECT sum(reserve_micro) AS n FROM ai_requests').get().n,100000);});
test('deletion removes private records and public contributions but preserves anonymous cost accounting',async t=>{const env=fixture(t),a=await activate(env);await req(env,'/api/posts','POST',{text:'公开测试',tag:'训练交流'},a.cookie);await req(env,'/api/ai/plan','POST',input(),a.cookie);assert.equal((await req(env,'/api/account','DELETE',{},a.cookie)).status,200);assert.equal((await req(env,'/api/bootstrap','GET',undefined,a.cookie)).body.active,false);assert.equal((await req(env,'/api/posts')).body.posts.length,0);const ledger=env.DB.sqlite.prepare('SELECT owner_id,result_json,reserve_micro FROM ai_requests').get();assert.ok(ledger.owner_id.startsWith('deleted:'));assert.equal(ledger.result_json,null);assert.equal(ledger.reserve_micro,100000);});
