import React,{useEffect,useRef,useState} from 'react';
import {useApp,Icon,Picture,Empty,Button,TextButton,photo,download} from './App.jsx';
import {uid,isoDate,exercises,makePlan,secondsElapsed,duration,csvForLogs,initialData,lessonContent} from './domain.mjs';
import {CloudDialog,AiDialog,EventRegistration} from './Connected.jsx';
const titles={cloud:'云端保存与数据管理',ai:'AI 训练计划',eventRegistration:'免费测试报名',profile:'我的训练档案',reason:'推荐依据与适用范围',library:'寻找适合你的动作',templates:'选择训练模板',session:'专注这一组',finish:'完成这次训练',post:'分享今天的小小进步',comments:'聊聊这条动态',event:'周末山野同行',rules:'活动抽奖机制',weight:'记录身体数据',data:'我的数据管理',about:'欢迎来到练遇',privacy:'数据与隐私',share:'分享练遇',chat:'训练使用帮助',log:'训练记录详情',delete:'删除这条记录？',reset:'清除本机体验数据？',discard:'丢弃本次训练？'};
export function Dialogs(){const a=useApp();if(!a.modal)return null;return <Dialog key={a.modal.type} app={a}/>;}
function Dialog({app:a}){const {modal:m,setModal,data,setData,profile,rec,today,announce,go,applyRec,communityTab,setSelectedDate,setMonth,restUntil,setRestUntil,tick}=a;const ref=useRef(null);const close=()=>setModal(null);
useEffect(()=>{ref.current.showModal();const original=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=original;};},[]);
const [search,setSearch]=useState(''),[muscle,setMuscle]=useState('全部'),[equipment,setEquipment]=useState('全部'),[question,setQuestion]=useState(''),[messages,setMessages]=useState([]);
function saveProfile(e){e.preventDefault();const f=new FormData(e.currentTarget);const p={...profile,name:f.get('name').trim(),sex:f.get('sex'),age:Number(f.get('age')),weight:Number(f.get('weight')),height:Number(f.get('height')),years:Number(f.get('years')),goal:f.get('goal'),equipment:f.get('equipment'),minutes:Number(f.get('minutes')),days:Number(f.get('days')),city:f.get('city').trim(),bio:f.get('bio').trim()};setData(d=>({...d,profile:p}));close();announce('个人档案已更新，保存状态见页面顶部。');}
function pause(){setData(d=>({...d,session:{...d.session,running:!d.session.running,elapsedMs:d.session.running?d.session.elapsedMs+Date.now()-d.session.startedAt:d.session.elapsedMs,startedAt:Date.now()}}));}
function checkSet(i){const s=data.session,wasDone=s.plan[s.index].done[i];setData(d=>({...d,session:{...d.session,plan:d.session.plan.map((e,j)=>j===d.session.index?{...e,done:e.done.map((done,k)=>k===i?!done:done)}:e)}}));if(!wasDone)setRestUntil(Date.now()+s.plan[s.index].rest*1000);}
function finish(e){e.preventDefault();const s=data.session,f=new FormData(e.currentTarget),completed=s.plan.reduce((sum,x)=>sum+x.done.filter(Boolean).length,0);if(!completed){announce('请先记录至少一组完成的动作。');return;}const record={id:s.id,title:s.title,date:s.date,finishedAt:new Date().toISOString(),seconds:secondsElapsed(s),completedSets:completed,effort:f.get('effort'),note:f.get('note').trim(),exercises:s.plan.map(x=>({name:x.name,sets:x.done.filter(Boolean).length,reps:x.reps,weight:x.weight})).filter(x=>x.sets>0)};setData(d=>({...d,logs:d.logs.some(l=>l.id===record.id)?d.logs:[record,...d.logs],session:null}));setRestUntil(null);setSelectedDate(record.date);setMonth(record.date);close();go('progress');announce('这一次努力，已为你记下。');}
function interest(id,title,kind){if(!data.interests.some(x=>x.id===id))setData(d=>({...d,interests:[...d.interests,{id,title,kind,date:today}]}));announce('意向已保存至当前浏览器，未提交主办方。');}
const list=exercises.filter(e=>(muscle==='全部'||e.muscle===muscle)&&(equipment==='全部'||e.equipment===equipment)&&(e.name+e.detail).includes(search));
return <dialog aria-labelledby="modal-title" ref={ref} className={'modal '+(['library','course','session'].includes(m.type)?'wide':'')} onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close();}}><header className="modal-head"><h2 id="modal-title">{m.type==='exercise'?m.exercise.name:m.type==='course'?m.course.name:titles[m.type]||'练遇'}</h2><button className="icon-btn" aria-label="关闭弹窗" onClick={close}><Icon name="X" size={23}/></button></header><div className="modal-body">
{m.type==='cloud'&&<CloudDialog/>}{m.type==='ai'&&<AiDialog/>}{m.type==='eventRegistration'&&<EventRegistration/>}{m.type==='profile'&&<form className="form" onSubmit={saveProfile}><p className="form-intro">用一点了解，让训练更适合你。启用云端后会保存到云端，个人资料不会自动公开。</p><div className="form-grid"><label>昵称<input name="name" defaultValue={profile.name} placeholder="怎么称呼你" required maxLength={24}/></label><label>性别<select name="sex" defaultValue={profile.sex}>{['未填写','女性','男性','其他 / 不愿透露'].map(x=><option key={x}>{x}</option>)}</select></label><label>年龄<input name="age" type="number" min="18" max="100" required defaultValue={profile.age}/></label><label>体重（kg）<input name="weight" type="number" min="20" max="300" step="0.1" required defaultValue={profile.weight}/></label><label>身高（cm）<input name="height" type="number" min="100" max="230" required defaultValue={profile.height}/></label><label>训练年限<input name="years" type="number" min="0" max="60" step="0.5" required defaultValue={profile.years}/></label><label>训练目标<select name="goal" defaultValue={profile.goal}>{['建立习惯','增肌力量','体重管理','提升体能'].map(x=><option key={x}>{x}</option>)}</select></label><label>可用器械<select name="equipment" defaultValue={profile.equipment}>{['自重','哑铃','弹力带','健身房'].map(x=><option key={x}>{x}</option>)}</select></label><label>每次可用时间<select name="minutes" defaultValue={profile.minutes}>{[15,20,30,35,45,60].map(x=><option key={x} value={x}>{x} 分钟</option>)}</select></label><label>每周训练天数<select name="days" defaultValue={profile.days}>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x} 天</option>)}</select></label><label>城市（选填）<input name="city" maxLength={30} defaultValue={profile.city} placeholder="无需填写具体地址"/></label></div><label>自我介绍（选填）<textarea name="bio" maxLength={180} defaultValue={profile.bio} placeholder="喜欢的运动、想建立的习惯…"/></label><p className="hint">性别不会单独决定训练强度；体重不用于自动推算负重。当前规则适用于成年人。</p><Button className="full" type="submit">保存个人档案<Icon name="Check"/></Button></form>}
{m.type==='reason'&&<><div className="notice"><Icon name="Info"/>此处展示基础规则建议；个性化 AI 计划可在首页另行生成。</div><h3>为什么是这个计划？</h3><ol className="reason-list">{rec.reasons.map(r=><li key={r}>{r}</li>)}</ol><p>参考 Trainer Skill 的档案、状态、记录和反馈流程。这里的规则用于体验，没有经过个体运动处方验证；需要依据身体能力调整。</p><p>若有疼痛或持续不适，请先暂停训练并寻求专业评估。</p><div className="resource-links"><a href="https://github.com/Yuvasee/trainer" target="_blank" rel="noreferrer">Trainer 项目<Icon name="ArrowRight"/></a><a href="https://www.who.int/news-room/fact-sheets/detail/physical-activity" target="_blank" rel="noreferrer">WHO 身体活动资料<Icon name="ArrowRight"/></a></div><Button className="full" disabled={rec.blocked} onClick={applyRec}>使用这份计划</Button></>}
{m.type==='exercise'&&<><Picture ex={m.exercise} className="detail-photo"/><div className="exercise-tags"><span>{m.exercise.muscle}</span><span>{m.exercise.equipment}</span><span>动作示意</span></div><h3>动作要点</h3><ol className="reason-list">{m.exercise.steps.map(s=><li key={s}>{s}</li>)}</ol><p className="hint">示意图片为生成素材，不能用于判断动作是否标准。选择稳定、舒适的动作范围。</p><Button className="full" onClick={()=>{setData(d=>({...d,plan:[...d.plan,{...m.exercise,key:uid()}]}));close();announce('动作已添加到自主训练计划。');}}>加入我的训练<Icon name="Plus"/></Button></>}
{m.type==='library'&&<><div className="search-field"><Icon name="MagnifyingGlass"/><input placeholder="搜索动作或肌群" aria-label="搜索动作" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="library-filters"><label>肌群<select value={muscle} onChange={e=>setMuscle(e.target.value)}>{['全部','下肢','背部','胸部','肩部','手臂','核心'].map(x=><option key={x}>{x}</option>)}</select></label><label>器械<select value={equipment} onChange={e=>setEquipment(e.target.value)}>{['全部','自重','哑铃','弹力带','健身房'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="library-results">{list.length?list.map(e=><div className="library-row" key={e.id}><Picture ex={e}/><div><strong>{e.name}</strong><small>{e.muscle} · {e.equipment}</small></div><Button secondary className="small-button" aria-label={`添加${e.name}`} onClick={()=>{setData(d=>({...d,plan:[...d.plan,{...e,key:uid()}]}));announce(`${e.name}已添加`);}}><Icon name="Plus"/>添加</Button></div>):<Empty icon="MagnifyingGlass" title="没有找到匹配动作">试试其他名称，或把筛选条件改为「全部」。</Empty>}</div><Button className="full" onClick={close}>完成选择 · 已选 {data.plan.length} 个动作</Button></>}
{m.type==='templates'&&<><p className="form-intro">选择模板会替换当前编辑中的计划，不影响已完成的历史记录。</p>{[['全身基础','goblet,row,incline','哑铃＋自重 · 3 个动作'],['居家无器械','squat,incline,bridge,deadbug','自重 · 4 个动作'],['基础拉力训练','bandrow,squat,deadbug','弹力带＋自重 · 3 个动作']].map(([title,ids,subtitle])=><button className="template-row" key={title} onClick={()=>{setData(d=>({...d,plan:makePlan(ids.split(',')),planName:title}));close();announce('已载入模板，可继续调整。');}}><Icon name="Barbell" size={26}/><span><strong>{title}</strong><small>{subtitle}</small></span><Icon name="CaretRight"/></button>)}</>}
{m.type==='session'&&data.session&&(()=>{const s=data.session,e=s.plan[s.index];return <><div className="session-top"><span>{s.title}</span><strong>{duration(secondsElapsed(s,tick))}</strong><Button secondary className="small-button" onClick={pause}><Icon name={s.running?'Pause':'Play'}/>{s.running?'暂停计时':'继续计时'}</Button></div><div className="session-exercise"><Picture ex={e}/><div><span className="eyebrow">动作 {s.index+1} / {s.plan.length}</span><h2>{e.name}</h2><p>{e.sets} 组 × {e.reps} 次 · {e.weight?`${e.weight} kg`:'自重 / 自选轻重量'}</p><p>{e.steps[0]}</p></div></div><div className="sets-list">{e.done.map((done,i)=><button key={i} aria-pressed={done} className={done?'done':''} onClick={()=>checkSet(i)}><span>第 {i+1} 组</span><strong>{e.reps} 次</strong><span>{done?'已完成':'标记完成'}<Icon name="CheckCircle" size={24} weight={done?'fill':'regular'}/></span></button>)}</div>{restUntil&&<div className="rest-timer"><Icon name="Timer"/>组间休息<strong>{Math.max(0,Math.ceil((restUntil-tick)/1000))} 秒</strong><TextButton onClick={()=>setRestUntil(null)}>跳过</TextButton></div>}<div className="session-navigation"><Button secondary disabled={!s.index} onClick={()=>{setData(d=>({...d,session:{...d.session,index:s.index-1}}));setRestUntil(null);}}><Icon name="CaretLeft"/>上个动作</Button>{s.index<s.plan.length-1?<Button onClick={()=>{setData(d=>({...d,session:{...d.session,index:s.index+1}}));setRestUntil(null);}}>下个动作<Icon name="CaretRight"/></Button>:<Button onClick={()=>setModal({type:'finish'})}>完成训练<Icon name="Check"/></Button>}</div><div className="session-footer"><TextButton onClick={()=>setModal({type:'finish'})}>提前结束并保存</TextButton><TextButton onClick={()=>setModal({type:'discard'})}>丢弃本次</TextButton></div><p className="hint small">关闭弹窗后训练仍可继续；计时与勾选会自动保存，云端状态见页面顶部。</p></>;})()}
{m.type==='finish'&&data.session&&<form className="form" onSubmit={finish}><div className="finish-summary"><Icon name="CheckCircle" size={45} weight="light"/><h3>为自己，留下一次记录。</h3><p>已完成 {data.session.plan.reduce((sum,e)=>sum+e.done.filter(Boolean).length,0)} 组 · 用时 {duration(secondsElapsed(data.session,tick))}</p></div><label>这次感觉如何？<select name="effort">{['适中','轻松','有挑战','过于吃力'].map(x=><option key={x}>{x}</option>)}</select></label><label>留一句给下次的自己<textarea name="note" maxLength={300} placeholder="动作感受、下次想调整的地方…"/></label><Button className="full" type="submit">保存训练与打卡<Icon name="Check"/></Button><Button secondary className="full" type="button" onClick={()=>setModal({type:'session'})}>返回训练</Button></form>}
{m.type==='discard'&&<><p>本次未保存的训练会被清除，历史记录不受影响。</p><Button className="full" onClick={()=>{setData(d=>({...d,session:null}));setRestUntil(null);close();announce('本次训练已丢弃。');}}>确认丢弃</Button><Button secondary className="full" onClick={()=>setModal({type:'session'})}>继续训练</Button></>}
{m.type==='post'&&<form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),text=f.get('text').trim();if(!text)return;setData(d=>({...d,posts:[{id:uid(),name:profile.name||'我的训练日常',text,tag:f.get('tag'),date:today,sample:false},...d.posts]}));close();announce('动态已保存在本地体验区，未向其他人发布。');}}><div className="notice"><Icon name="LockKey"/>这是本地发帖体验，其他访客不会看到。</div><label>话题<select name="tag" defaultValue={communityTab==='全部'?'训练交流':communityTab}>{['训练交流','饮食分享','找搭子',...(profile.dating?['交友']:[])].map(x=><option key={x}>{x}</option>)}</select></label><label>今天想分享什么？<textarea name="text" required maxLength={1000} rows={6} placeholder="一个动作的进步，一顿认真准备的饭…"/></label><Button className="full" type="submit">保存本地动态<Icon name="ArrowRight"/></Button></form>}
{m.type==='comments'&&<><p className="comment-original">{m.post.text}</p><div className="comments-list">{(data.comments[m.post.id]||[]).length?(data.comments[m.post.id]||[]).map(c=><div key={c.id}><strong>{c.name}</strong><p>{c.text}</p><small>{c.date} · 本地评论</small></div>):<p className="muted">还没有评论，写下你的想法。</p>}</div><form className="comment-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),text=f.get('comment').trim();if(!text)return;setData(d=>({...d,comments:{...d.comments,[m.post.id]:[...(d.comments[m.post.id]||[]),{id:uid(),name:profile.name||'我',text,date:today}]}}));e.currentTarget.reset();}}><input name="comment" aria-label="评论内容" required maxLength={300} placeholder="友善交流，尊重彼此"/><Button type="submit">保存评论</Button></form><p className="hint">评论仅在当前浏览器显示。</p></>}
{m.type==='event'&&<><img className="modal-hero" src={photo('outdoor')} alt="山野徒步"/><div className="notice">示例活动 · 当前不接受正式报名或付款。</div><h3>轻徒步、户外打卡与运动交流</h3><p>由主办方组织运动博主同行。路线、日期、带队者与实际名额公布后再开放报名。</p><dl className="details-list"><div><dt>当前阶段</dt><dd>活动概念与流程体验</dd></div><div><dt>费用及包含项目</dt><dd>待正式活动公布</dd></div><div><dt>免费名额与抽奖</dt><dd>条件、名额及开奖时间待公布</dd></div><div><dt>交通装备与取消</dt><dd>以正式活动规则为准</dd></div></dl><Button className="full" onClick={()=>{interest('outdoor','周末山野同行','活动');close();}}>保存活动意向<Icon name="BookmarkSimple"/></Button><TextButton onClick={()=>setModal({type:'rules'})}>查看抽奖机制说明<Icon name="CaretRight"/></TextButton></>}
{m.type==='rules'&&<><div className="notice">功能规划说明 · 目前没有真实抽奖或中奖名额。</div><ol className="reason-list"><li><strong>资格与权益分开说明。</strong>正式活动将明确哪些课程购买或报名可获得资格。购买课程不等于中奖，不把抽奖次数作为独立商品。</li><li><strong>规则在参与前公开。</strong>主办方、时间、名额、条件、每人次数，以及取消退款后的资格处理均需写明。</li><li><strong>结果有记录。</strong>正式抽奖需由服务端执行并保留审核记录；结果只公开获授权的脱敏信息。</li><li><strong>免费范围说清楚。</strong>交通、住宿、餐食、装备和保险是否包含，需要逐项列出。</li></ol><p className="hint">真实付费及促销活动尚未启用；正式上线前需按经营地区核实规则。本页面不产生订单、抽奖资格或中奖结果。</p></>}
{m.type==='course'&&<><div className="course-detail"><img src={photo(m.course.image)} alt={m.course.name}/><div><span className="eyebrow">{m.course.tag} · 免费图文</span><h3>{m.course.name}</h3><p>{m.course.desc}</p><span className="muted">免费学习 · 学完可记录进度</span></div></div><div className="lesson-layout"><div className="lesson-list">{m.course.lessons.map((l,i)=><button key={l} className={m.lesson===i?'active':''} onClick={()=>setModal({...m,lesson:i})}><span>{String(i+1).padStart(2,'0')}</span>{l}<Icon name="CaretRight" size={16}/></button>)}</div><article className="lesson-content"><span className="eyebrow">第 {m.lesson+1} 节 · 图文课程</span><h3>{m.course.lessons[m.lesson]}</h3><p>{lessonContent[m.course.lessons[m.lesson]]||m.course.intro}</p><p>练习后可在「自主训练」记录完成情况，在「我的数据」回顾变化。</p><TextButton onClick={()=>{close();go('plan');}}>去安排一次训练<Icon name="ArrowRight"/></TextButton></article></div><div className="course-actions"><p>已完成 {(data.courseProgress?.[m.course.id]||[]).length} / {m.course.lessons.length} 节 · 免费学习</p><Button onClick={()=>{setData(d=>{const done=d.courseProgress?.[m.course.id]||[];return {...d,courseProgress:{...d.courseProgress,[m.course.id]:done.includes(m.lesson)?done:[...done,m.lesson]}};});announce('本节学习进度已记录。');}} disabled={(data.courseProgress?.[m.course.id]||[]).includes(m.lesson)}>{(data.courseProgress?.[m.course.id]||[]).includes(m.lesson)?'本节已完成':'标记本节完成'}<Icon name="Check"/></Button></div></>}
{m.type==='weight'&&<form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,weights:[{id:uid(),date:f.get('date'),weight:Number(f.get('weight')),waist:f.get('waist')?Number(f.get('waist')):null,fat:f.get('fat')?Number(f.get('fat')):null},...d.weights]}));close();announce('身体数据已记录。');}}><p className="form-intro">只填写实际测量的数据，未测量的项目可以留空。</p><label>记录日期<input name="date" type="date" defaultValue={today} max={today} required/></label><label>体重（kg）<input name="weight" type="number" min="20" max="300" step="0.1" defaultValue={data.weights[0]?.weight||profile.weight} required/></label><div className="form-grid"><label>腰围（cm，选填）<input name="waist" type="number" min="30" max="250" step="0.1"/></label><label>体脂率（%，选填）<input name="fat" type="number" min="2" max="70" step="0.1"/></label></div><Button className="full" type="submit">保存记录<Icon name="Check"/></Button></form>}
{m.type==='data'&&<><p>启用云端后，记录会保存至本站并通过当前浏览器的访问凭证找回；更换设备或清理 Cookie 后不能自动恢复身份。请妥善保管导出的备份。</p><div className="data-actions"><Button secondary className="full" onClick={()=>download(`练遇-训练记录-${today}.csv`,csvForLogs(data.logs),'text/csv;charset=utf-8')}><Icon name="DownloadSimple"/>导出训练记录 CSV</Button><Button secondary className="full" onClick={()=>download(`练遇-完整备份-${today}.json`,JSON.stringify(data,null,2))}><Icon name="DownloadSimple"/>导出完整数据 JSON</Button><Button secondary className="full" onClick={()=>setModal({type:a.cloud.active?'cloud':'reset'})}><Icon name="Trash"/>管理或清除我的数据</Button></div><p className="hint">完整备份含个人档案及健康记录，请勿直接公开分享。</p></>}
{m.type==='reset'&&<><p>将删除当前浏览器中练遇的档案、计划、训练、动态与意向。请先导出需要保留的内容。</p><Button secondary className="full" onClick={()=>download('练遇-备份.json',JSON.stringify(data,null,2))}>先导出备份</Button><Button className="full" onClick={()=>{setData(initialData());setRestUntil(null);close();go('coach');announce('本机体验数据已清除。');}}>确认清除本机数据</Button></>}
{m.type==='delete'&&<><p>仅删除当前浏览器中的这条记录。</p><Button className="full" onClick={()=>{setData(d=>({...d,[m.collection]:d[m.collection].filter(x=>x.id!==m.id)}));close();}}>确认删除</Button></>}
{m.type==='about'&&<><div className="about-brand"><strong>练遇</strong><span>LIANYU</span></div><h3>今天，练得刚刚好。</h3><p>面向学生和上班族的免费训练工具。支持自主编排、训练计时、记录和免费图文课程。</p><p>云端、AI 和社区是否已启用，以当前页面状态为准。AI 使用 DeepSeek 生成结构化计划；首页基础动作仍来自可查看依据的规则建议。</p><p>活动报名为明确标注的测试流程，没有实际线下名额或付款。当前通过浏览器身份保存云端记录，跨设备登录和身份找回仍待接入。</p></>}
{m.type==='privacy'&&<><h3>你的记录，由你掌握。</h3><p>未启用云端时，个人训练数据保存在当前浏览器。启用前会单独说明并征求同意；启用后，档案、睡眠、身体数据、计划、训练和课程进度保存到本站云端，个人记录不会自动公开。</p><p>每次 AI 生成前需要确认发送范围：必要的身体与训练条件、今日状态会交给 DeepSeek 处理，不发送昵称、城市、自我介绍和社区正文。</p><p>公开社区只展示主动发布的昵称、话题、正文、评论和点赞。请勿发布他人隐私；可删除自己的动态或举报内容。</p><p>访问凭证保存在当前浏览器的 Cookie 中，前端脚本不能读取它。共用同一浏览器的人可能访问这些记录；更换设备或清理 Cookie 后目前无法自动找回身份。</p><p>可导出私人备份、删除自己的云端资料。删除后保留已移除档案和内容的调用计费记录以核对额度。托管和模型服务会处理提供服务所需的请求；本站没有接入广告或第三方分析脚本。</p><Button secondary className="full" onClick={()=>setModal({type:'data'})}>管理我的数据<Icon name="ArrowRight"/></Button></>}
{m.type==='share'&&<><p>复制网址即可分享网站，个人记录不会包含在链接中。</p><input aria-label="网站分享地址" readOnly value={location.origin+location.pathname} onFocus={e=>e.target.select()}/></>}
{m.type==='chat'&&<><div className="notice">训练使用帮助 · 以下回复来自固定说明。</div><div className="chat-messages"><div className="assistant-message">你可以问「今天怎么练」「睡不好怎么办」或「怎么记录进步」。</div>{messages.map((m,i)=><div key={i} className={m.role==='user'?'user-message':'assistant-message'}>{m.text}</div>)}</div><form className="comment-form" onSubmit={e=>{e.preventDefault();const q=question.trim();if(!q)return;const answer=/痛|伤|晕/.test(q)?'出现疼痛、头晕或其他不适时，请暂停训练。持续不适请寻求专业评估。':/睡|累|疲|恢复/.test(q)?'先更新首页的睡眠、精力与恢复状态。疲惫时可以减量或休息，不必为了打卡勉强训练。':/记录|进步|数据/.test(q)?'在自主训练中点击开始训练，逐组勾选完成。保存后记入我的数据，也可以手动记录体重与腰围。':/今天|计划|怎么练/.test(q)?`${rec.title}：${rec.blocked?rec.reasons[0]:`当前规则建议 ${rec.minutes} 分钟，${rec.intensity}。${rec.reasons[1]} 点击首页“查看依据”查看并使用计划。`}`:'此帮助面板只介绍训练安排、恢复与记录。个性化训练请打开首页的“生成 AI 计划”。';setMessages(ms=>[...ms,{role:'user',text:q},{role:'assistant',text:answer}]);setQuestion('');}}><input aria-label="向训练助手提问" maxLength={300} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="今天怎么练？"/><Button type="submit">发送</Button></form></>}
{m.type==='log'&&<><h3>{m.log.title}</h3><p>{m.log.date} · {duration(m.log.seconds)} · {m.log.effort}</p><div className="log-details">{m.log.exercises.map((e,i)=><div key={i}><strong>{e.name}</strong><span>{e.sets} 组 × {e.reps} 次 · {e.weight?`${e.weight} kg`:'自重 / 未设重量'}</span></div>)}</div>{m.log.note&&<p>{m.log.note}</p>}<p className="hint">时长来自训练计时，组数来自你的完成勾选。</p></>}
</div></dialog>;
}
